# Generated by Django 5.0.3 on 2025-01-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="category_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.IntegerField()),
                (
                    "veg_nonveg_egg",
                    models.CharField(
                        choices=[
                            ("veg", "veg only"),
                            ("non_veg", "non-veg only"),
                            ("egg", "contains egg"),
                        ],
                        default="veg",
                        max_length=10,
                    ),
                ),
                ("avg_time_taken", models.IntegerField(null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="menu_images/"),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True, related_name="item", to="home.category"
                    ),
                ),
            ],
        ),
    ]
