# Generated by Django 5.0.3 on 2025-01-21 17:05

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="date",
            field=models.DateTimeField(default=orders.models.get_current_datetime),
        ),
        migrations.AlterField(
            model_name="orders",
            name="time",
            field=models.TimeField(default=orders.models.get_current_time),
        ),
    ]
