# Generated by Django 5.0.3 on 2025-02-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_orders_date_alter_orders_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
