# Generated by Django 5.0.3 on 2025-01-10 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_remove_orders_items_alter_orders_date_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
