# Generated by Django 5.0.3 on 2025-01-19 13:26

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_orders_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
